apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 1h0m0s
  values:
    podSecurityStandard: restricted
    validationFailureAction: enforce
    