apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "7.0.4"
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    adminPassword: strongpassword
    replicas: 1
    serviceMonitor:
      enabled: true
      interval: 30s
      labels:
        tier: cluster
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        provider:
          allowUiUpdates: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          uid: prometheus_ds
          url: http://kube-prometheus-stack-prometheus.monitoring:9090
          jsonData:
            exemplarTraceIdDestinations:
              - name: trace_id
                datasourceUid: tempo_ds
        - name: IstioPrometheus
          type: prometheus
          access: proxy
          uid: istio_prometheus_ds
          url: http://prometheus.istio-system:9090
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
        - name: 'istio'
          orgId: 1
          folder: 'Istio'
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/istio
    plugins:
    - grafana-worldmap-panel
    - grafana-clock-panel
    - grafana-piechart-panel
    - grafana-kubernetes-app
    - camptocamp-prometheus-alertmanager-datasource
    - ryantxu-ajax-panel
    - novatec-sdg-panel
    dashboards:
      default:
        kube-state-metrics:
          gnetId: 13332
          revision: 23
          datasource: Prometheus
        prometheus-node-exporter:
          gnetId: 1860
          revision: 30
          datasource: Prometheus
        prometheus:
          gnetId: 1662
          revision: 2
          datasource: Prometheus
        alertmanager-stats:
          gnetId: 9578
          revision: 4
          datasource: Prometheus
        k8s-system-api-server:
          gnetId: 15761
          revision: 11
          datasource: Prometheus
        k8s-system-coredns:
          gnetId: 15762
          revision: 11
          datasource: Prometheus
        k8s-views-global:
          gnetId: 15757
          revision: 22
          datasource: Prometheus
        k8s-views-namespaces:
          gnetId: 15758
          revision: 15
          datasource: Prometheus
        k8s-views-nodes:
          gnetId: 15759
          revision: 14
          datasource: Prometheus
        k8s-views-pods:
          gnetId: 15760
          revision: 16
          datasource: Prometheus
        k8s-views-deploy-ss-ds:
          gnetId: 8588
          revision: 1
          datasource: Prometheus
      istio:
        istio-workload:
          gnetId: 7630
          revision: 182
          datasource: Prometheus
        istio-mesh:
          gnetId: 7639
          revision: 182
          datasource: Prometheus
        istio-service:
          gnetId: 7636
          revision: 182
          datasource: Prometheus
        istio-control-plane:
          gnetId: 7645
          revision: 182
          datasource: Prometheus
        istio-performance:
          gnetId: 11829
          revision: 182
          datasource: Prometheus
