apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "52.1.0"
  interval: 1h0m0s
  timeout: 30m
  install:
    remediation:
      retries: 3
  values:
    commonLabels:
      tier: cluster
    grafana:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kube-state-metrics:
      prometheus:
        monitor:
          enabled: true
          additionalLabels:
            tier: cluster
    prometheus:
      prometheusSpec:
        replicas: 2
        scrapeInterval: 15s
        scrapeTimeout: 10s
        evaluationInterval: 15s
        retention: 40d
        ruleSelector:
          matchLabels:
            tier: cluster
        serviceMonitorSelector:
          matchLabels:
            tier: cluster
        podMonitorSelector:
          matchLabels:
            tier: cluster