name: Build and Push echo version service

on: 
  push:
    paths:
      - applications/echo-version/**
    branches: [main]
  pull_request:
    paths:
      - applications/echo-version/**
    branches: [main]

env:
  BUILD_DIR: applications/echo-version

jobs:
  build:
    uses: ./.github/workflows/build_and_push.yml