apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-version
  labels:
    app: echo-version
spec:
  serviceAccountName: applications
  selector:
    matchLabels:
      app: echo-version
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4195"
      labels:
        app: echo-version
    spec:
      containers:
      - name: echo
        image: ""
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4195
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: 4195
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 4195
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 130m
            memory: 200Mi