apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-version
spec:
  template:
    spec:
      containers:
      - name: echo
        image: 0.1.30 # {"$imagepolicy": "applications:echo-version:tag"}
