name: Build and Push echo version service

on: 
  push:
    paths:
      - applications/echo-version/**
    branches: [main]
  pull_request:
    paths:
      - applications/echo-version/**
    branches: [main]

jobs:
  build:
    permissions: 
      contents: read
      packages: write 
    uses: ./.github/workflows/build_and_push.yml
    with:
      path: applications/echo-version